### PR TITLE
Add ruby implementation of slack output

### PR DESCRIPTION
**Pull request by trozamon**
I wrote a slack output plugin a while ago, and have been running it in production for around 6 months.

### CODE REVIEW

**Comment by ghost** [comment]
Jenkins standing by to test this. If you aren't a maintainer, you can ignore this comment. Someone with commit access, please review this and clear it for Jenkins to run; then  say 'jenkins, test it'.

**Comment by talevy** [comment]
Lets first check on #1 and we can see how we can include your contribution for improvements. thanks!

**Comment by talevy** [comment]
Closing due to inactivity and no CLA signed. feel free to re-open to move this forward!

**Comment by trozamon** [comment]
#1 looks like a much better implementation anyways

**Pull request closed without merging**
