### PR TITLE
Initial commit from the logstash-output-slack repo

### PR DESCRIPTION
**Pull request by cyli**
Merged https://github.com/cyli/logstash-output-slack master branch in, and attempted to merge the two `README.md`'s.

The link to all asciidoc documentation in the bootstrap README seems to be broken.

Copied description from https://github.com/elastic/logstash/issues/3000:

I've attempted to create a new plugin as per [these instructions](http://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_output_plugin.html#_publishing_to_ulink_url_http_rubygems_org_rubygems_org_ulink_4) for pushing log messages to slack:

https://github.com/cyli/logstash-output-slack

I've manually tested this, but it doesn't really have fantastic rspec coverage (not sure how to test logging on errors, for instance), and would love a review (as I don't really know Ruby) + moving this to [logstash-plugins](https://github.com/logstash-plugins)  :)

This would supercede [this PR](https://github.com/elastic/logstash-contrib/pull/120).

---

This change is [Reviewable](https://reviewable.io/reviews/logstash-plugins/logstash-output-slack/1)

### CODE REVIEW

**Comment by devinrsmith** [comment]
+1

**Comment by cyli** [comment]
Apologies, ok, fixed conflicts, and updated with changes from other repo.  Question - is travis turned on for this repo?

**Comment by ghost** [comment]
Jenkins standing by to test this. If you aren't a maintainer, you can ignore this comment. Someone with commit access, please review this and clear it for Jenkins to run; then  say 'jenkins, test it'.

**Comment by cyli** [comment]
Will fix merge conflicts later this evening. (~8-10 hours from this comment)

**Comment by suyograo** [comment]
Thanks for this @cyli. You have included a commit from @spang who's not signed our CLA, so I can't merge this immediately.

@spang could you please sign our CLA (contributor's agreement) here: https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by spang** [comment]
Done!

**Comment by talevy** [comment]
@spang thank you for the contribution! looks like this was never merged for some reason. please rebase and we can go ahead and merge!

**Comment by karmi** [comment]
Hi @cyli, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-output-slack/pull/1.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Pull request merged**
